"""Prompt engineering engine for casino & sports-betting media generation.

Design notes
------------
- Prompts are composed in English: both DALL-E 3 and Luma/Runway respond
  measurably better to detailed English prompts than to translated ones,
  regardless of the operator's own language. The Telegram UI itself is
  fully Turkish (see labels.py) — only the text sent to the AI providers
  is English.
- Every theme has a short, reusable "core concept" template plus a shared
  "house style" suffix so all output stays visually consistent with a
  premium, Pragmatic-Play-like casino aesthetic (glossy 3D renders, warm
  gold + royal blue palette, crisp readable typography, cinematic studio
  lighting).
- Image prompts, video motion prompts and sticker prompts are generated by
  layered helper functions rather than duplicated templates, so tweaking
  the house style in one place updates every output type consistently.
"""

from __future__ import annotations

from dataclasses import dataclass

from bot.utils.constants import CasinoTheme, OutputType, SportsTheme

# --- Shared brand language ---------------------------------------------------

PRAGMATIC_PALETTE = (
    "a premium Pragmatic Play-style palette of warm metallic gold (#FFD700), "
    "deep royal blue (#0B1F6B), and bright white highlights"
)

HOUSE_STYLE_SUFFIX = (
    "ultra-detailed 3D glossy render, octane render quality, studio-grade "
    "cinematic lighting with strong rim light, high dynamic range, "
    "polished reflective surfaces, vibrant saturated colors, "
    f"{PRAGMATIC_PALETTE}, sharp focus, 8k resolution, premium online casino "
    "key-art quality, symmetrical balanced composition"
)

# Things we never want in generated output. For DALL-E 3 (no native negative
# prompt support) this is folded into the positive prompt as an instruction;
# for Luma/Runway it is passed through their dedicated negative_prompt field.
NEGATIVE_PROMPT_KEYWORDS = (
    "blurry, low-resolution, extra limbs, distorted anatomy, watermark, "
    "signature, text artifacts, garbled text, cropped frame, dull flat "
    "lighting, oversaturated noise, jpeg compression artifacts, low-effort "
    "clip-art look"
)


def _clean(text: str) -> str:
    return " ".join(text.split())


def _compose(*parts: str) -> str:
    """Join non-empty prompt fragments with ", " and normalize whitespace."""
    return _clean(", ".join(p.strip() for p in parts if p and p.strip()))


# --- Casino theme templates ---------------------------------------------------

_CASINO_CORE_CONCEPTS: dict[CasinoTheme, str] = {
    CasinoTheme.SLOT_KEY_ART: (
        "key art poster for a premium online slot machine game called "
        "'{subject}', centered oversized slot reel symbols bursting forward "
        "with motion, glowing gold coin and gemstone accents, ornate royal "
        "frame border"
    ),
    CasinoTheme.FREESPIN_RAIN: (
        "explosive 'FREE SPINS' celebration scene for the slot game "
        "'{subject}', dozens of spinning gold coins and sparkling diamonds "
        "raining down mid-air, bold glowing 'FREE SPINS' banner text, "
        "radial light burst background"
    ),
    CasinoTheme.MASCOT_3D: (
        "a 3D glossy cartoon mascot character representing the slot game "
        "'{subject}', dynamic heroic pose, expressive charismatic face, "
        "glossy toy-like plastic/porcelain material shading, standing on a "
        "podium of gold coins"
    ),
    CasinoTheme.JACKPOT_BANNER: (
        "a 'MEGA JACKPOT WIN' celebration banner for the slot game "
        "'{subject}', giant glowing jackpot number, fireworks of gold coins "
        "and confetti exploding outward, triumphant royal atmosphere"
    ),
}


def build_casino_prompt(
    theme: CasinoTheme,
    subject: str,
    custom_details: str | None = None,
) -> str:
    """Build a DALL-E 3 ready casino image prompt for the given theme.

    Args:
        theme: Which casino visual archetype to generate.
        subject: Short description of the game/brand, e.g. "Aztec Gold
            Deluxe slot" or "generic tiger-themed slot" if no specific game
            name was given by the user.
        custom_details: Optional free-text the user typed to steer the
            result further (e.g. "tiger mascot, jungle background").
    """
    core = _CASINO_CORE_CONCEPTS[theme].format(subject=subject.strip() or "a premium slot game")
    return _compose(
        core,
        custom_details or "",
        HOUSE_STYLE_SUFFIX,
        f"avoid: {NEGATIVE_PROMPT_KEYWORDS}",
    )


# --- Sports betting theme templates ------------------------------------------

_SPORTS_CORE_CONCEPTS: dict[SportsTheme, str] = {
    SportsTheme.MATCHDAY_BANNER: (
        "dramatic sports betting matchday banner featuring '{subject}', two "
        "athletes/teams facing off in a versus composition, stadium floodlight "
        "atmosphere, bold dynamic typography space for team names"
    ),
    SportsTheme.ODDS_BOARD: (
        "a glowing digital sportsbook odds board displaying betting odds for "
        "'{subject}', stadium at night in the background, holographic "
        "scoreboard-style UI panels with glowing numbers"
    ),
    SportsTheme.WINNING_TICKET: (
        "a triumphant celebration scene of a winning sports bet slip for "
        "'{subject}', gold confetti and light rays bursting around a glowing "
        "betting ticket, cash and trophy accents"
    ),
    SportsTheme.LIVE_ACTION: (
        "a frozen high-speed action shot of '{subject}' at the most intense "
        "moment of the match, dynamic motion blur on the background, crowd "
        "roaring in the stands, dramatic stadium lighting"
    ),
}


def build_sports_prompt(
    theme: SportsTheme,
    subject: str,
    custom_details: str | None = None,
) -> str:
    """Build a DALL-E 3 ready sports-betting image prompt for the given theme."""
    core = _SPORTS_CORE_CONCEPTS[theme].format(
        subject=subject.strip() or "a major football match"
    )
    return _compose(
        core,
        custom_details or "",
        HOUSE_STYLE_SUFFIX,
        f"avoid: {NEGATIVE_PROMPT_KEYWORDS}",
    )


# --- Video / motion prompt layering ------------------------------------------

_DEFAULT_MOTION_HINTS: dict[CasinoTheme | SportsTheme, str] = {
    CasinoTheme.SLOT_KEY_ART: "slow cinematic push-in camera move, symbols gently pulsing with light",
    CasinoTheme.FREESPIN_RAIN: "coins and gems continuously falling and bouncing, looping seamlessly",
    CasinoTheme.MASCOT_3D: "mascot performs a subtle idle animation, breathing motion, confident wink",
    CasinoTheme.JACKPOT_BANNER: "explosive burst of coins and confetti expanding outward from center",
    SportsTheme.MATCHDAY_BANNER: "slow parallax camera drift between the two competing sides",
    SportsTheme.ODDS_BOARD: "odds numbers flicker and update, subtle holographic flicker animation",
    SportsTheme.WINNING_TICKET: "confetti bursts and light rays pulse outward in a continuous loop",
    SportsTheme.LIVE_ACTION: "fast dynamic camera whip-pan following the motion, crowd lights flashing",
}


def build_video_motion_prompt(
    base_image_prompt: str,
    theme: CasinoTheme | SportsTheme | None = None,
    motion_hint: str | None = None,
) -> str:
    """Layer a motion/animation description on top of a base image prompt.

    Used for image-to-video providers (Luma Dream Machine, Runway Gen-3
    Alpha) which take a source image plus a text prompt describing desired
    camera/scene motion.
    """
    hint = motion_hint or (_DEFAULT_MOTION_HINTS.get(theme) if theme else None) or (
        "smooth, subtle looping motion, cinematic camera movement"
    )
    return _compose(
        base_image_prompt,
        f"animation direction: {hint}",
        "seamless loop, smooth 24fps motion, no jarring cuts",
    )


def get_video_negative_prompt() -> str:
    """Negative prompt text for providers that accept a dedicated field."""
    return NEGATIVE_PROMPT_KEYWORDS


# --- Sticker prompt layering --------------------------------------------------


def build_sticker_prompt(base_prompt: str) -> str:
    """Adapt a base prompt so the subject is easy to cut out cleanly with rembg.

    Stickers need a single, centered, well-separated subject on a plain
    (ideally solid-color) background so the local rembg background-removal
    step produces a clean silhouette.
    """
    return _compose(
        base_prompt,
        "single centered subject, isolated on a plain uncluttered solid-color "
        "background, clear well-defined edges, no overlapping foreground "
        "elements touching the frame border",
    )


# --- High-level request/response types ---------------------------------------


@dataclass(frozen=True, slots=True)
class PromptResult:
    """A fully composed prompt plus provider-specific metadata."""

    positive_prompt: str
    negative_prompt: str
    output_type: OutputType


def build_prompt_for_casino(
    theme: CasinoTheme,
    subject: str,
    output_type: OutputType,
    custom_details: str | None = None,
) -> PromptResult:
    """One-stop builder: casino theme + desired output type -> final prompt."""
    base = build_casino_prompt(theme, subject, custom_details)
    if output_type is OutputType.STICKER:
        base = build_sticker_prompt(base)
    elif output_type is OutputType.VIDEO:
        base = build_video_motion_prompt(base, theme=theme)
    return PromptResult(
        positive_prompt=base,
        negative_prompt=get_video_negative_prompt(),
        output_type=output_type,
    )


def build_prompt_for_sports(
    theme: SportsTheme,
    subject: str,
    output_type: OutputType,
    custom_details: str | None = None,
) -> PromptResult:
    """One-stop builder: sports theme + desired output type -> final prompt."""
    base = build_sports_prompt(theme, subject, custom_details)
    if output_type is OutputType.STICKER:
        base = build_sticker_prompt(base)
    elif output_type is OutputType.VIDEO:
        base = build_video_motion_prompt(base, theme=theme)
    return PromptResult(
        positive_prompt=base,
        negative_prompt=get_video_negative_prompt(),
        output_type=output_type,
    )
